### ISSUE TITLE
unable to resolve module url from "...node_modules/@tonybadguy/call-me-maybe..."

### ISSUE THREAD

**Issue by mixophrygian** [tonybadguy/yelp-fusion#12]
Hi there, thanks for the library.  I'm attempting to pull this into an old version of react-native and consistently get 
```
Unable to resolve module url from /Users/***/MyAwesomeProject/node_modules/@tonybadguy/call-me-maybe/lib/request-filters/url-params.js: 
Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/url and its parent directories
```
This is just using a basic import of `import yelp from 'yelp-fusion'`

It may well be that my packager just isn't able to deal with this but I'd rather write my request by hand  than have to go through another react-native upgrade.  Any easy fixes for this?

react-native 0.29.0, node 9.0.0, npm 6.4.1

Already done the recommended node_module reinstall, clearing watchman watches, reseting the packager cache. Thanks.

**Comment by tonybadguy** [comment]
hmm hard to say without looking at your project. What does your package.json look like?

**Comment by tonybadguy** [comment]
This library is meant to be hosted on node.js as a backend service only. Not too familiar with react-native, so you're on your own, but seems like there are all sorts of problems with react-native and node.js in general:

https://github.com/facebook/react-native/issues/4968
https://hackernoon.com/using-core-node-js-modules-in-react-native-apps-64acd4d07140

You might have to do some workarounds, especially on an old version of react-native. Did it work on the latest version?

**Comment by mixophrygian** [comment]
It's cool, I decided to just DIY the query string and pass the Authorization Header to fetch.  Thanks anyway.
