### ISSUE TITLE
"SyntaxError: Use of const in strict mode." with "const _send = require('@tonybadguy/call-me-maybe');"

### ISSUE THREAD

**Issue by tdotholla** [tonybadguy/yelp-fusion#2]
i get this error when starting up. 
cleared npm cache and reinstalled node, updated to node 7+

`
W20161231-01:39:21.561(-5)? (STDERR) /Users/ME/Sites/SITE/app/.meteor/local/build/programs/server/packages/modules.js:3537
W20161231-01:39:21.562(-5)? (STDERR) const _send = require('@tonybadguy/call-me-maybe');
W20161231-01:39:21.562(-5)? (STDERR) ^^^^^
W20161231-01:39:21.598(-5)? (STDERR) SyntaxError: Use of const in strict mode.
W20161231-01:39:21.599(-5)? (STDERR)     at /Users/ME/Sites/SITEapp/.meteor/local/build/programs/server/boot.js:292:30
W20161231-01:39:21.599(-5)? (STDERR)     at Array.forEach (native)
W20161231-01:39:21.599(-5)? (STDERR)     at Function._.each._.forEach (/Users/ME/.meteor/packages/meteor-tool/.1.3.5_1.17pn3ki++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20161231-01:39:21.600(-5)? (STDERR)     at /Users/ME/Sites/SITE/app/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
`

it looks like an issue in the package itself...

**Comment by tdotholla** [comment]
my confusion, 
i updated node, but meteor still using old version... 
sleep is catching up to me, sorry all.

**Comment by tonybadguy** [comment]
👍
