### ISSUE TITLE
How to get all reviews

### ISSUE THREAD

**Issue by anjaneyulu-nyros** [tonybadguy/yelp-fusion#3]
I am getting 3 comments and related data only how to get all reviews

**Comment by tonybadguy** [comment]
Per [yelp api documentation](https://www.yelp.com/developers/documentation/v3/business_reviews) at most 3 reviews are returned for a business. You may want to contact them for a server-side feature request.

Closing as this is not related to the client code.

**Comment by anjaneyulu-nyros** [comment]
Ok Thank you

**Comment by anjaneyulu-nyros** [comment]
Can I get the Menus
