### ISSUE TITLE
Yelp Fusion "OAUTH_TOKEN_ENDPOINT_DEPRECATED"

### ISSUE THREAD

**Issue by Jeffchiucp** [tonybadguy/yelp-fusion#7]
I encountered this bug when I tried to use yelp api fusion.
The wrapper for our Oauth 2 becomes depreciated, wondering if there's any fix for #6 

 body: '{"error": {"code": "OAUTH_TOKEN_ENDPOINT_DEPRECATED", "description": "The oauth2 token endpoint has been deprecated and removed; you must use your API key for authentication instead. Please see https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going for info & migration steps"}}' }, 

Prior to December 7, 2017 the API used OAuth 2.0 to authenticate requests to the API. In an effort to simplify authentication, starting March 1, 2018 the API no longer uses OAuth 2.0 for requests and moved over to only API Keys.

With OAuth 2.0 the process to authenticate was:

Get your Client ID and client secret from the Manage App page.
Make a request to the token endpoint with your Client ID and client secret to get an access token.
Put the access token inside of the request header as "Authorization: Bearer <YOUR ACCESS TOKEN>" and make requests against the API.
With just API Keys the process to authenticate is:

Get your API Key from the Manage App page.
Put the API Key in the request header as "Authorization: Bearer <YOUR API KEY>".
And that's it! You no longer need to make a request to the token endpoint to get an access token. Your API Key does not expire like the access tokens used to, so you don't need to worry about generating new ones. Note that the API Key is not a drop in replacement for the client secret. Using the API Key as a client secret in the token endpoint will not work.

**Comment by tonybadguy** [comment]
Yes, the old OAuth endpoint is no longer supported on the Yelp API backend since March 1st. If you are still using a v1 version of this client library, it will no longer work.

1. You'll need to upgrade to the latest version of this library (v2.0.3)
2. Follow the yelp documentation to get your API key.
3. You can then use the client like this:
```
'use strict';

const yelp = require('yelp-fusion');

const client = yelp.client(apiKey);

client.search({
  term:'Four Barrel Coffee',
  location: 'san francisco, ca'
}).then(response => {
  console.log(response.jsonBody.businesses[0].name);
}).catch(e => {
  console.log(e);
});
```

**Comment by Jeffchiucp** [comment]
this resolved my issue. Thanks.
