### ISSUE TITLE
Is there a work around for the CORS issue?

### ISSUE THREAD

**Issue by ArtisJr** [tonybadguy/yelp-fusion#8]
I'm currently trying to implement Yelp into a React application and I am receiving a CORS error trying to access Yelp from the client-side. Do you know of any possible way to work around this?

**Comment by ArtisJr** [comment]
I will have to look into using JSONP or potentially rethinking the small project. I was using ReactJS, React-Router, and Request-Promise (to get Yelp Information).

**Comment by tonybadguy** [comment]
What kind of project are you working on?

While JSONP will get you there, it's kind of a hack, so unless you're just playing around I wouldn't recommending going that route. Yelp's api intentionally disabled cross origin requests, so I think the right thing to do is write a server-side endpoint that will relay the request -- this endpoint will have to be hosted on the same domain as your frontend or hosted on a different domain but return a CORS header that allow requests from your frontend domain.
